pages:
  stage: deploy
  script:
    - echo ""
  artifacts:
    paths:
      - public
  only:
    # Trigger a new build and deploy only when there is a push to the
    # below branch(es)
    - master
